id: A3F1C7C43
title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
type: translation
pechas:
- I8B973D0B
- I8DA14977
- I74994411
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:32:04.396181
  last_modified_at: 2023-01-04 11:32:04.396190
  collections:
  - Chokgyur Dechen Lingpa
  - Works of Tibetan Masters
alignment_to_base:
  I8B973D0B/107E: EEE5
  I8DA14977/0900: EEE5
  I74994411/DAAF: EEE5
